In [1]:
import pandas as pd; pd.set_option('display.max_columns', None)
import cmlreaders as cml
import numpy as np

In [8]:
df = cml.get_data_index()
df['experiment'].unique()

array(['ltpFR', 'ltpFR2', 'VFFR', 'ltpRepFR', 'NiclsCourierClosedLoop',
       'NiclsCourierReadOnly', 'ltpDelayRepFRReadOnly',
       'CourierReinstate1', 'ltpDBOY1', 'prelim', 'EFRCourierOpenLoop',
       'EFRCourierReadOnly', 'FR1', 'FR2', 'PAL1', 'YC1', 'PAL2',
       'catFR1', 'YC2', 'catFR2', 'PS1', 'ICatFR1', 'ICatFR6', 'IFR1',
       'IFR6', 'PS3', 'PS2', 'TH1', 'FR3', 'PS2.1', 'PAL3', 'TH3', 'OPS',
       'RepFR1', 'catFR3', 'FR5', 'PS4_catFR', 'THR', 'PS4_FR', 'PAL5',
       'THR1', 'catFR5', 'PS4_catFR5', 'FR6', 'PS5_catFR', 'catFR6',
       'TICL_FR', 'LocationSearch', 'TICL_catFR', 'DBOY1', 'CatFR6',
       'RepFR2', 'CPS', 'pyFR'], dtype=object)

In [9]:
df = df[df['experiment'] == 'CourierReinstate1']
df[:10]

,Recognition,all_events,contacts,experiment,import_type,localization,math_events,montage,original_experiment,original_session,pairs,ps4_events,session,subject,subject_alias,system_version,task_events
7492,NaN,protocols/ltp/subjects/LTP564/experiments/Cour...,NaN,CourierReinstate1,build,0,NaN,0,NaN,1,NaN,NaN,1,LTP564,LTP564,NaN,protocols/ltp/subjects/LTP564/experiments/Cour...
7493,NaN,protocols/ltp/subjects/LTP564/experiments/Cour...,NaN,CourierReinstate1,build,0,NaN,0,NaN,3,NaN,NaN,3,LTP564,LTP564,NaN,protocols/ltp/subjects/LTP564/experiments/Cour...
7494,NaN,protocols/ltp/subjects/LTP564/experiments/Cour...,NaN,CourierReinstate1,build,0,NaN,0,NaN,4,NaN,NaN,4,LTP564,LTP564,NaN,protocols/ltp/subjects/LTP564/experiments/Cour...
7495,NaN,protocols/ltp/subjects/LTP564/experiments/Cour...,NaN,CourierReinstate1,build,0,NaN,0,NaN,5,NaN,NaN,5,LTP564,LTP564,NaN,protocols/ltp/subjects/LTP564/experiments/Cour...
7496,NaN,protocols/ltp/subjects/LTP565/experiments/Cour...,NaN,CourierReinstate1,build,0,NaN,0,NaN,2,NaN,NaN,2,LTP565,LTP565,NaN,protocols/ltp/subjects/LTP565/experiments/Cour...
7497,NaN,protocols/ltp/subjects/LTP565/experiments/Cour...,NaN,CourierReinstate1,build,0,NaN,0,NaN,3,NaN,NaN,3,LTP565,LTP565,NaN,protocols/ltp/subjects/LTP565/experiments/Cour...
7498,NaN,protocols/ltp/subjects/LTP565/experiments/Cour...,NaN,CourierReinstate1,build,0,NaN,0,NaN,5,NaN,NaN,5,LTP565,LTP565,NaN,protocols/ltp/subjects/LTP565/experiments/Cour...
7499,NaN,protocols/ltp/subjects/LTP566/experiments/Cour...,NaN,CourierReinstate1,build,0,NaN,0,NaN,3,NaN,NaN,3,LTP566,LTP566,NaN,protocols/ltp/subjects/LTP566/experiments/Cour...
7500,NaN,protocols/ltp/subjects/LTP566/experiments/Cour...,NaN,CourierReinstate1,build,0,NaN,0,NaN,4,NaN,NaN,4,LTP566,LTP566,NaN,protocols/ltp/subjects/LTP566/experiments/Cour...
7501,NaN,protocols/ltp/subjects/LTP567/experiments/Cour...,NaN,CourierReinstate1,build,0,NaN,0,NaN,2,NaN,NaN,2,LTP567,LTP567,NaN,protocols/ltp/subjects/LTP567/experiments/Cour...

In [10]:
all_evs = []

for _, row in df.iterrows():
    subject = row['subject']
    session = row['session']
    reader = cml.CMLReader(subject=subject, experiment='CourierReinstate1', session=session)
    evs = reader.load('events')
    all_evs.append(evs)

all_evs = pd.concat(all_evs)
word_evs = all_evs[all_evs['type'] == 'WORD']

In [11]:
word_count = word_evs.groupby('item').size()
rec_count = word_evs[word_evs['recalled'] == 1].groupby('item').size()
df2 = pd.DataFrame({'presented': word_count, 'recalled': rec_count})
df2['recall_rate'] = df2['recalled'] / df2['presented']
pd.set_option('display.max_rows', None)

In [13]:
df2.sort_values(by='recall_rate', ascending=False)

                   presented  recalled  recall_rate
item
POOLTABLE                  3       3.0     1.000000
WASHINGMACHINE             4       4.0     1.000000
PEANUTBUTTER               3       3.0     1.000000
PINGPONGPADDLES            3       3.0     1.000000
VENDINGMACHINE             3       3.0     1.000000
GORILLA                  139     126.0     0.906475
GIRAFFE                  149     132.0     0.885906
RHINO                    137     118.0     0.861314
CHIMPANZEE               139     117.0     0.841727
TIGER                    134     112.0     0.835821
HONEY                    140     117.0     0.835714
KNIFE                    137     114.0     0.832117
WATER                    142     118.0     0.830986
ORCA                     142     118.0     0.830986
SQUID                    141     117.0     0.829787
BEAR                     141     117.0     0.829787
FORK                     143     118.0     0.825175
XYLOPHONE                147     121.0     0.823129
ZEBRA                    134     110.0     0.820896
CAT                      145     118.0     0.813793
SPOON                    144     117.0     0.812500
STRUDEL                  143     116.0     0.811189
FOX                      143     116.0     0.811189
SHARK                    141     114.0     0.808511
SQUIRREL                 144     116.0     0.805556
AVOCADO                  142     114.0     0.802817
SALAD                    145     116.0     0.800000
ORANGE                   144     115.0     0.798611
JELLYFISH                139     111.0     0.798561
HORSE                    136     108.0     0.794118
WALRUS                   140     111.0     0.792857
SOUP                     147     116.0     0.789116
PENGUIN                  137     108.0     0.788321
RAMEN                    146     115.0     0.787671
PASTA                    141     111.0     0.787234
FLAMINGO                 131     103.0     0.786260
SNAKE                    145     114.0     0.786207
BED                      149     117.0     0.785235
PANDA                    139     109.0     0.784173
SHORTCAKE                148     116.0     0.783784
VIOLIN                   143     112.0     0.783217
DOG                      147     115.0     0.782313
OCTOPUS                  148     115.0     0.777027
DOLPHIN                  148     115.0     0.777027
BOWL                     139     108.0     0.776978
ANTEATER                 137     106.0     0.773723
PLATE                    149     115.0     0.771812
LION                     149     115.0     0.771812
BOAR                     148     114.0     0.770270
PIG                      142     109.0     0.767606
EAGLE                    137     105.0     0.766423
COFFEE                   141     108.0     0.765957
WEIGHTS                  145     111.0     0.765517
PICKAXE                  138     105.0     0.760870
SHIRT                    132     100.0     0.757576
CHICKEN                  139     105.0     0.755396
LIQUOR                   141     106.0     0.751773
PIDGEON                  145     109.0     0.751724
SHOPPINGCART               4       3.0     0.750000
RECORDPLAYER               4       3.0     0.750000
COFFEEMACHINE              4       3.0     0.750000
ORANGEJUICE                4       3.0     0.750000
CHALKBOARD                 4       3.0     0.750000
MUSICSTAND                 4       3.0     0.750000
GOAT                     144     108.0     0.750000
DRUMSET                    4       3.0     0.750000
FISHINGROD                 4       3.0     0.750000
DISHSOAP                   4       3.0     0.750000
FISH                     149     111.0     0.744966
CRATE                    137     102.0     0.744526
SPIDER                   156     116.0     0.743590
PIANO                    144     107.0     0.743056
BIRD                     138     102.0     0.739130
HIPPO                    145     107.0     0.737931
WATERMELON               141     104.0     0.737589
SINK                     141     104.0     0.737589
SKATEBOARD               143     105.0     0.734266
PEAR                     150     110.0     0.733333
SMOOTHIE                 146     107.0     0.732877
PICTURE                  142     104.0     0.732394
WINE                     148     108.0     0.729730
CHILI_PEPPERS            147     107.0     0.727891
SODA                     132      96.0     0.727273
METRONOME                146     106.0     0.726027
TORCH                    149     108.0     0.724832
KETCHUP                  145     105.0     0.724138
FLOWER                   147     106.0     0.721088
YOGURT                   147     106.0     0.721088
PANTS                    136      98.0     0.720588
CHIMES                   150     108.0     0.720000
CROISSANT                135      97.0     0.718519
TELEVISION               145     104.0     0.717241
RABBIT                   145     104.0     0.717241
PIE                      140     100.0     0.714286
DEER                     140     100.0     0.714286
BASKET                   143     102.0     0.713287
PRINTER                  146     104.0     0.712329
BAGEL                    139      99.0     0.712230
COW                      139      99.0     0.712230
ELEPHANT                 145     103.0     0.710345
SHEEP                    148     105.0     0.709459
CHAIR                    147     104.0     0.707483
GUITAR                   139      98.0     0.705036
PARROT                   142     100.0     0.704225
OVEN                     142     100.0     0.704225
SKULL                    147     103.0     0.700680
CAN                      133      93.0     0.699248
ASHTRAY                  136      95.0     0.698529
TROMBONE                 136      95.0     0.698529
MIXER                    149     104.0     0.697987
BOOKS                    139      97.0     0.697842
CEREAL                   142      99.0     0.697183
BUFFALO                  142      99.0     0.697183
SEAL                     148     103.0     0.695946
COUCH                    151     105.0     0.695364
PINEAPPLE                141      98.0     0.695035
BANANA                   141      98.0     0.695035
MICROPHONE               134      93.0     0.694030
DISH_SOAP                145     100.0     0.689655
KEYBOARD                 135      93.0     0.688889
WAFFLE                   153     105.0     0.686275
MUSHROOMS                146     100.0     0.684932
BUTTERFLY                138      94.0     0.681159
GLOBE                    141      96.0     0.680851
MEAT                     144      98.0     0.680556
POT                      142      96.0     0.676056
CLOCK                    145      98.0     0.675862
TREADMILL                132      89.0     0.674242
MICROWAVE                148      99.0     0.668919
TABLE                    141      94.0     0.666667
ORANGE_JUICE             137      91.0     0.664234
UMBRELLA                 133      88.0     0.661654
CACTUS                   147      97.0     0.659864
TREE                     143      94.0     0.657343
PUMPKIN                  137      90.0     0.656934
LOG                      150      98.0     0.653333
WASHING_MACHINE          141      92.0     0.652482
COFFEE_MACHINE           132      86.0     0.651515
BLENDER                  146      95.0     0.650685
POPCORN                  146      95.0     0.650685
VENDING_MACHINE          140      91.0     0.650000
LAMP                     141      91.0     0.645390
SANDWICH                 140      90.0     0.642857
PEANUT_BUTTER            148      95.0     0.641892
CAMERA                   143      91.0     0.636364
PLANT                    140      89.0     0.635714
HEADPHONES               136      86.0     0.632353
CARROT                   145      91.0     0.627586
SCOOTER                  144      90.0     0.625000
TRASHCAN                 144      90.0     0.625000
TOILET                   141      88.0     0.624113
GOOSE                    138      86.0     0.623188
HAMPER                   148      92.0     0.621622
BAG                      144      89.0     0.618056
DOG_FOOD                 144      89.0     0.618056
REFRIGERATOR             149      92.0     0.617450
DONUT                    138      85.0     0.615942
WATER_JUG                140      86.0     0.614286
KETTLE                   138      84.0     0.608696
MUSIC_STAND              143      87.0     0.608392
TRAIN                    135      82.0     0.607407
SHOPPING_CART            137      83.0     0.605839
SOFA                     147      89.0     0.605442
TOASTER                  139      84.0     0.604317
RUBIKS_CUBE              137      82.0     0.598540
FIRE_EXTINGUISHER        142      84.0     0.591549
CHALK_BOARD              133      78.0     0.586466
RECORD_PLAYER            141      82.0     0.581560
COMPUTER                 143      83.0     0.580420
HELICOPTER               147      85.0     0.578231
POOL_TABLE               137      78.0     0.569343
DRUM_SET                 144      80.0     0.555556
PING_PONG_PADDLES        142      78.0     0.549296
TEAPOT                   144      79.0     0.548611
FRIDGE                   139      75.0     0.539568
SOCCERBALL               140      74.0     0.528571
WARNING_SIGN             131      68.0     0.519084
WARNINGSIGN                4       2.0     0.500000
CHILIPEPPERS               4       2.0     0.500000
PAPER_TOWELS             142      71.0     0.500000
DRUMS                    133      65.0     0.488722
FISHING_ROD              138      65.0     0.471014
DOGFOOD                    3       1.0     0.333333
WATERJUG                   3       1.0     0.333333
PAPERTOWELS                4       1.0     0.250000
SLIDE                    136      18.0     0.132353
STOVE                    141       1.0     0.007092
AMPLIFIER                138       NaN          NaN
APPLE                    137       NaN          NaN
AXE                      143       NaN          NaN
BASKETBALLHOOP             4       NaN          NaN
BASKETBALL_HOOP          136       NaN          NaN
DOOR                     141       NaN          NaN
FIREEXTINGUISHER           4       NaN          NaN
IRONINGBOARD               4       NaN          NaN
IRONING_BOARD            137       NaN          NaN
RUBIKSCUBE                 4       NaN          NaN
SHOVEL                   141       NaN          NaN

In [16]:
df2.to_csv('recall_rates_by_word.csv')